### ISSUE TITLE
Encounter with 500 Internal Server Error when requesting toolbench_url

### ISSUE THREAD

**Issue by Dr-Left** [zhichengg/StableToolBench#9]
```
# config.yml
api_key: ***
api_base: ***
model: gpt-3.5-turbo
temperature: 0
toolbench_url: http://8.218.239.54:8080/rapidapi
tools_folder: "./tools"
cache_folder: "./tool_response_cache"
is_save: true
port: 8080
```

When the stabletoolbench server requests http://8.218.239.54:8080/rapidapi, got a response:
```
statuscode: 500, Internal Server Error
```

Is the server down?

**Comment by zhichengg** [comment]
Hi, 

The server works well now.  You can use the following code to test the status of the server:
```
import requests

url  = "http://8.218.239.54:8080/rapidapi"
payload = {

    "category": "Food",
    "tool_name": "yummly",
    "api_name": "categories_list",
    "tool_input": "{}",
    "strip": "truncate",
    'toolbench_key': ''
}

headers = {'toolbench_key': ''}
response = requests.post(url, json=payload, headers=headers)
print(response.text)
```

The error may be because the tool you are calling is not available on RapidAPI now. However, this error was not designed to trigger simulation. I have added this to simulation cases now.

Many thanks!

**Comment by Dr-Left** [comment]
Thank you! Yes, the api I called is no longer available on RapidAPI. Thank you for fixing the codebase!
